name: todo6
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.0
  firebase_analytics: ^11.3.0
  easy_date_timeline: ^1.1.3
  cloud_firestore: ^5.4.0
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  provider: ^6.1.2  # Correctly add the provider dependency here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
